# Generated by Django 4.2 on 2024-08-15 09:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'DEPARTMENTS',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LOCATIONS',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'META_DATA',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SUBCATEGORY',
            },
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_upper_name_subcategory'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.category'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.department'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.location'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.subcategory'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_upper_name_location'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_upper_name_department'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_upper_name_category'),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('location', 'department', 'category', 'sub_category')},
        ),
    ]
