# Generated by Django 4.2 on 2024-08-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_categories', to='meta.category'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_departments', to='meta.department'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_locations', to='meta.location'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_subcategories', to='meta.subcategory'),
        ),
    ]
