# Generated by Django 4.2 on 2024-08-15 09:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.metadata')),
            ],
            options={
                'db_table': 'PRODUCTS',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_upper_name_product'),
        ),
    ]
